# Generated by bin/claude-completion-gen — do not edit by hand.
# Source: claude --help (version 2.1.156).
typeset -g _claude_data_version='2.1.156'

typeset -ga _claude_subcommands=(
  'agents:Manage background agents'
  'auth:Manage authentication'
  'auto-mode:Inspect auto mode classifier'
  'doctor:Check the health of your Claude Code'
  'install:Install Claude Code native build. Use'
  'mcp:Configure and manage MCP servers'
  'plugin:Manage Claude Code plugins'
  'project:Manage Claude Code project state'
  'setup-token:Set up a long-lived authentication token'
  'ultrareview:Run a cloud-hosted multi-agent code'
  'update:Check for updates and install if'
)

typeset -ga _claude_flag_names=(
  '--add-dir'
  '--agent'
  '--agents'
  '--allow-dangerously-skip-permissions'
  '--allowed-tools'
  '--append-system-prompt'
  '--bare'
  '--betas'
  '--brief'
  '--chrome'
  '--continue'
  '--dangerously-skip-permissions'
  '--debug'
  '--debug-file'
  '--disable-slash-commands'
  '--disallowed-tools'
  '--effort'
  '--exclude-dynamic-system-prompt-sections'
  '--fallback-model'
  '--file'
  '--fork-session'
  '--from-pr'
  '--help'
  '--ide'
  '--include-hook-events'
  '--include-partial-messages'
  '--input-format'
  '--json-schema'
  '--max-budget-usd'
  '--mcp-config'
  '--mcp-debug'
  '--model'
  '--name'
  '--no-chrome'
  '--no-session-persistence'
  '--output-format'
  '--permission-mode'
  '--plugin-dir'
  '--plugin-url'
  '--print'
  '--prompt-suggestions'
  '--remote-control'
  '--remote-control-session-name-prefix'
  '--replay-user-messages'
  '--resume'
  '--session-id'
  '--setting-sources'
  '--settings'
  '--strict-mcp-config'
  '--system-prompt'
  '--tmux'
  '--tools'
  '--verbose'
  '--version'
  '--worktree'
)

typeset -gA _claude_flag_desc=(
  '--add-dir' 'Additional directories to allow tool access to'
  '--agent' 'Agent for the current session. Overrides the '\''agent'\'' setting.'
  '--agents' 'JSON object defining custom agents (e.g. '\''{"reviewer": {"description": "Reviews code", "prompt": "You are a code reviewer"}}'\'')'
  '--allow-dangerously-skip-permissions' 'Enable bypassing all permission checks as an option, without it being enabled by default. Recommended only for sandboxes with no internet access.'
  '--allowed-tools' 'Comma or space-separated list of tool names to allow (e.g. "Bash(git *) Edit")'
  '--append-system-prompt' 'Append a system prompt to the default system prompt'
  '--bare' 'Minimal mode: skip hooks, LSP, plugin sync, attribution, auto-memory, background prefetches, keychain reads, and CLAUDE.md auto-discovery. Sets CLAUDE_CODE_SIMPLE=1. Anthropic auth is strictly ANTHROPIC_API_KEY or apiKeyHelper via --settings (OAuth and keychain are never read). 3P providers (Bedrock/Vertex/Foundry) use their own credentials. Skills still resolve via /skill-name. Explicitly provide context via: --system-prompt[-file], --append-system-prompt[-file], --add-dir (CLAUDE.md dirs), --mcp-config, --settings, --agents, --plugin-dir.'
  '--betas' 'Beta headers to include in API requests (API key users only)'
  '--brief' 'Enable SendUserMessage tool for agent-to-user communication'
  '--chrome' 'Enable Claude in Chrome integration'
  '--continue' 'Continue the most recent conversation in the current directory'
  '--dangerously-skip-permissions' 'Bypass all permission checks. Recommended only for sandboxes with no internet access.'
  '--debug' 'Enable debug mode with optional category filtering (e.g., "api,hooks" or "!1p,!file")'
  '--debug-file' 'Write debug logs to a specific file path (implicitly enables debug mode)'
  '--disable-slash-commands' 'Disable all skills'
  '--disallowed-tools' 'Comma or space-separated list of tool names to deny (e.g. "Bash(git *) Edit")'
  '--effort' 'Effort level for the current session (low, medium, high, xhigh, max)'
  '--exclude-dynamic-system-prompt-sections' 'Move per-machine sections (cwd, env info, memory paths, git status) from the system prompt into the first user message. Improves cross-user prompt-cache reuse. Only applies with the default system prompt (ignored with --system-prompt). (default: false)'
  '--fallback-model' 'Enable automatic fallback to specified model when the default model is overloaded or not available (only works with --print)'
  '--file' 'File resources to download at startup. Format: file_id:relative_path (e.g., --file file_abc:doc.txt file_def:img.png)'
  '--fork-session' 'When resuming, create a new session ID instead of reusing the original (use with --resume or --continue)'
  '--from-pr' 'Resume a session linked to a PR by PR number/URL, or open interactive picker with optional search term'
  '--help' 'Display help for command'
  '--ide' 'Automatically connect to IDE on startup if exactly one valid IDE is available'
  '--include-hook-events' 'Include all hook lifecycle events in the output stream (only works with --output-format=stream-json)'
  '--include-partial-messages' 'Include partial message chunks as they arrive (only works with --print and --output-format=stream-json)'
  '--input-format' 'Input format (only works with --print): "text" (default), or "stream-json" (realtime streaming input) (choices: "text", "stream-json")'
  '--json-schema' 'JSON Schema for structured output validation. Example: {"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}'
  '--max-budget-usd' 'Maximum dollar amount to spend on API calls (only works with --print)'
  '--mcp-config' 'Load MCP servers from JSON files or strings (space-separated)'
  '--mcp-debug' '[DEPRECATED. Use --debug instead] Enable MCP debug mode (shows MCP server errors)'
  '--model' 'Model for the current session. Provide an alias for the latest model (e.g. '\''sonnet'\'' or '\''opus'\'') or a model'\''s full name (e.g. '\''claude-opus-4-8'\'').'
  '--name' 'Set a display name for this session (shown in the prompt box, /resume picker, and terminal title)'
  '--no-chrome' 'Disable Claude in Chrome integration'
  '--no-session-persistence' 'Disable session persistence - sessions will not be saved to disk and cannot be resumed (only works with --print)'
  '--output-format' 'Output format (only works with --print): "text" (default), "json" (single result), or "stream-json" (realtime streaming) (choices: "text", "json", "stream-json")'
  '--permission-mode' 'Permission mode to use for the session (choices: "acceptEdits", "auto", "bypassPermissions", "default", "dontAsk", "plan")'
  '--plugin-dir' 'Load a plugin from a directory or .zip for this session only (repeatable: --plugin-dir A --plugin-dir B.zip) (default: [])'
  '--plugin-url' 'Fetch a plugin .zip from a URL for this session only (repeatable: --plugin-url A --plugin-url B) (default: [])'
  '--print' 'Print response and exit (useful for pipes). Note: The workspace trust dialog is skipped when Claude is run in non-interactive mode (via -p, or when stdout is not a TTY, e.g. piped or redirected output). Only use this in directories you trust. Settings files that fail validation are silently ignored in this mode (no error dialog is shown).'
  '--prompt-suggestions' 'Enable prompt suggestions. In print/SDK mode, emits a prompt_suggestion message after each turn with a predicted next user prompt (choices: "true", "false", "1", "0", "yes", "no", "on", "off", preset: "true")'
  '--remote-control' 'Start an interactive session with Remote Control enabled (optionally named)'
  '--remote-control-session-name-prefix' 'Prefix for auto-generated Remote Control session names (default: hostname)'
  '--replay-user-messages' 'Re-emit user messages from stdin back on stdout for acknowledgment (only works with --input-format=stream-json and --output-format=stream-json)'
  '--resume' 'Resume a conversation by session ID, or open interactive picker with optional search term'
  '--session-id' 'Use a specific session ID for the conversation (must be a valid UUID)'
  '--setting-sources' 'Comma-separated list of setting sources to load (user, project, local).'
  '--settings' 'Path to a settings JSON file or a JSON string to load additional settings from'
  '--strict-mcp-config' 'Only use MCP servers from --mcp-config, ignoring all other MCP configurations'
  '--system-prompt' 'System prompt to use for the session'
  '--tmux' 'Create a tmux session for the worktree (requires --worktree). Uses iTerm2 native panes when available; use --tmux=classic for traditional tmux.'
  '--tools' 'Specify the list of available tools from the built-in set. Use "" to disable all tools, "default" to use all tools, or specify tool names (e.g. "Bash,Edit,Read").'
  '--verbose' 'Override verbose mode setting from config'
  '--version' 'Output the version number'
  '--worktree' 'Create a new git worktree for this session (optionally specify a name)'
)

typeset -gA _claude_flag_arg=(
  '--add-dir' 1
  '--agent' 1
  '--agents' 1
  '--allow-dangerously-skip-permissions' 0
  '--allowed-tools' 1
  '--append-system-prompt' 1
  '--bare' 0
  '--betas' 1
  '--brief' 0
  '--chrome' 0
  '--continue' 0
  '--dangerously-skip-permissions' 0
  '--debug' 1
  '--debug-file' 1
  '--disable-slash-commands' 0
  '--disallowed-tools' 1
  '--effort' 1
  '--exclude-dynamic-system-prompt-sections' 0
  '--fallback-model' 1
  '--file' 1
  '--fork-session' 0
  '--from-pr' 1
  '--help' 0
  '--ide' 0
  '--include-hook-events' 0
  '--include-partial-messages' 0
  '--input-format' 1
  '--json-schema' 1
  '--max-budget-usd' 1
  '--mcp-config' 1
  '--mcp-debug' 0
  '--model' 1
  '--name' 1
  '--no-chrome' 0
  '--no-session-persistence' 0
  '--output-format' 1
  '--permission-mode' 1
  '--plugin-dir' 1
  '--plugin-url' 1
  '--print' 0
  '--prompt-suggestions' 1
  '--remote-control' 1
  '--remote-control-session-name-prefix' 1
  '--replay-user-messages' 0
  '--resume' 1
  '--session-id' 1
  '--setting-sources' 1
  '--settings' 1
  '--strict-mcp-config' 0
  '--system-prompt' 1
  '--tmux' 0
  '--tools' 1
  '--verbose' 0
  '--version' 0
  '--worktree' 1
)

typeset -gA _claude_flag_short=(
  '--continue' '-c'
  '--debug' '-d'
  '--help' '-h'
  '--name' '-n'
  '--print' '-p'
  '--resume' '-r'
  '--version' '-v'
  '--worktree' '-w'
)

typeset -gA _claude_choices=(
  '--effort' 'low medium high xhigh max'
  '--input-format' 'text stream-json'
  '--output-format' 'text json stream-json'
  '--permission-mode' 'acceptEdits auto bypassPermissions default dontAsk plan'
  '--prompt-suggestions' 'true false 1 0 yes no on off'
)
